# Generated by Django 3.2 on 2022-09-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionattempt',
            name='succeed_at',
        ),
    ]
