# Generated by Django 3.2 on 2022-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_remove_subscriptionattempt_succeed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionattempt',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
