# Generated by Django 3.2 on 2022-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0007_subscriptionattempt_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='subscribed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
