# Generated by Django 3.2 on 2022-09-17 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_subscriptionattempt_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsubscriptionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_code', models.CharField(max_length=25, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='newsletter.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
